package Classes;



/**
 * Acteurfilm generated by hbm2java
 */
public class Acteurfilm  implements java.io.Serializable {


     private ActeurfilmId id;
     private Film film;
     private String personnage;

    public Acteurfilm() {
    }

	
    public Acteurfilm(ActeurfilmId id, Film film) {
        this.id = id;
        this.film = film;
    }
    public Acteurfilm(ActeurfilmId id, Film film, String personnage) {
       this.id = id;
       this.film = film;
       this.personnage = personnage;
    }
   
    public ActeurfilmId getId() {
        return this.id;
    }
    
    public void setId(ActeurfilmId id) {
        this.id = id;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    public String getPersonnage() {
        return this.personnage;
    }
    
    public void setPersonnage(String personnage) {
        this.personnage = personnage;
    }




}


