package Classes;


import java.math.BigDecimal;
import java.util.Date;

/**
 * Acteur generated by hbm2java
 */
public class Acteur  implements java.io.Serializable {


     private BigDecimal idacteur;
     private String nom;
     private Date anniversaire;
     private String lieu;
     private String photo;
     private String bio;

    public Acteur() {
    }

    public Acteur(String nom) {
        this.nom = nom;
    }

	
    public Acteur(BigDecimal idacteur) {
        this.idacteur = idacteur;
    }
    public Acteur(BigDecimal idacteur, String nom, Date anniversaire, String lieu, String photo, String bio) {
       this.idacteur = idacteur;
       this.nom = nom;
       this.anniversaire = anniversaire;
       this.lieu = lieu;
       this.photo = photo;
       this.bio = bio;
    }
   
    public BigDecimal getIdacteur() {
        return this.idacteur;
    }
    
    public void setIdacteur(BigDecimal idacteur) {
        this.idacteur = idacteur;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Date getAnniversaire() {
        return this.anniversaire;
    }
    
    public void setAnniversaire(Date anniversaire) {
        this.anniversaire = anniversaire;
    }
    public String getLieu() {
        return this.lieu;
    }
    
    public void setLieu(String lieu) {
        this.lieu = lieu;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getBio() {
        return this.bio;
    }
    
    public void setBio(String bio) {
        this.bio = bio;
    }




}


