package Classes;


import java.math.BigDecimal;

/**
 * ActeurfilmId generated by hbm2java
 */
public class ActeurfilmId  implements java.io.Serializable {


     private BigDecimal idacteur;
     private BigDecimal idfilm;

    public ActeurfilmId() {
    }

    public ActeurfilmId(BigDecimal idacteur, BigDecimal idfilm) {
       this.idacteur = idacteur;
       this.idfilm = idfilm;
    }
   
    public BigDecimal getIdacteur() {
        return this.idacteur;
    }
    
    public void setIdacteur(BigDecimal idacteur) {
        this.idacteur = idacteur;
    }
    public BigDecimal getIdfilm() {
        return this.idfilm;
    }
    
    public void setIdfilm(BigDecimal idfilm) {
        this.idfilm = idfilm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ActeurfilmId) ) return false;
		 ActeurfilmId castOther = ( ActeurfilmId ) other; 
         
		 return ( (this.getIdacteur()==castOther.getIdacteur()) || ( this.getIdacteur()!=null && castOther.getIdacteur()!=null && this.getIdacteur().equals(castOther.getIdacteur()) ) )
 && ( (this.getIdfilm()==castOther.getIdfilm()) || ( this.getIdfilm()!=null && castOther.getIdfilm()!=null && this.getIdfilm().equals(castOther.getIdfilm()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdacteur() == null ? 0 : this.getIdacteur().hashCode() );
         result = 37 * result + ( getIdfilm() == null ? 0 : this.getIdfilm().hashCode() );
         return result;
   }   


}


