package Classes;


import java.math.BigDecimal;

/**
 * Employe generated by hbm2java
 */
public class Employe  implements java.io.Serializable {


     private BigDecimal idmembre;
     private Membre membre;
     private String matricule;

    public Employe() {
    }

	
    public Employe(Membre membre) {
        this.membre = membre;
    }
    public Employe(Membre membre, String matricule) {
       this.membre = membre;
       this.matricule = matricule;
    }
   
    public BigDecimal getIdmembre() {
        return this.idmembre;
    }
    
    public void setIdmembre(BigDecimal idmembre) {
        this.idmembre = idmembre;
    }
    public Membre getMembre() {
        return this.membre;
    }
    
    public void setMembre(Membre membre) {
        this.membre = membre;
    }
    public String getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }




}


