package Classes;


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Forfait generated by hbm2java
 */
public class Forfait  implements java.io.Serializable {


     private BigDecimal idforfait;
     private String nom;
     private Double cout;
     private BigDecimal locationmaximale;
     private BigDecimal duree;
     private Set clients = new HashSet(0);

    public Forfait() {
    }

	
    public Forfait(BigDecimal idforfait) {
        this.idforfait = idforfait;
    }
    public Forfait(BigDecimal idforfait, String nom, Double cout, BigDecimal locationmaximale, BigDecimal duree, Set clients) {
       this.idforfait = idforfait;
       this.nom = nom;
       this.cout = cout;
       this.locationmaximale = locationmaximale;
       this.duree = duree;
       this.clients = clients;
    }
   
    public BigDecimal getIdforfait() {
        return this.idforfait;
    }
    
    public void setIdforfait(BigDecimal idforfait) {
        this.idforfait = idforfait;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Double getCout() {
        return this.cout;
    }
    
    public void setCout(Double cout) {
        this.cout = cout;
    }
    public BigDecimal getLocationmaximale() {
        return this.locationmaximale;
    }
    
    public void setLocationmaximale(BigDecimal locationmaximale) {
        this.locationmaximale = locationmaximale;
    }
    public BigDecimal getDuree() {
        return this.duree;
    }
    
    public void setDuree(BigDecimal duree) {
        this.duree = duree;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }




}


