package Classes;


import java.math.BigDecimal;
import java.util.Date;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private BigDecimal idlocation;
     private Membre membre;
     private Film film;
     private Date datelocation;

    public Location() {
    }

	
    public Location(BigDecimal idlocation) {
        this.idlocation = idlocation;
    }
    public Location(BigDecimal idlocation, Membre membre, Film film, Date datelocation) {
       this.idlocation = idlocation;
       this.membre = membre;
       this.film = film;
       this.datelocation = datelocation;
    }
   
    public BigDecimal getIdlocation() {
        return this.idlocation;
    }
    
    public void setIdlocation(BigDecimal idlocation) {
        this.idlocation = idlocation;
    }
    public Membre getMembre() {
        return this.membre;
    }
    
    public void setMembre(Membre membre) {
        this.membre = membre;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    public Date getDatelocation() {
        return this.datelocation;
    }
    
    public void setDatelocation(Date datelocation) {
        this.datelocation = datelocation;
    }




}


