package Classes;


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Membre generated by hbm2java
 */
public class Membre  implements java.io.Serializable {


     private BigDecimal idmembre;
     private String nomfamille;
     private String prenom;
     private String courriel;
     private String tel;
     private Date anniversaire;
     private String motdepasse;
     private Set locations = new HashSet(0);
     private Employe employe;
     private Client client;
     private Adresse adresse;

    public Membre() {
    }

	
    public Membre(BigDecimal idmembre) {
        this.idmembre = idmembre;
    }
    public Membre(BigDecimal idmembre, String nomfamille, String prenom, String courriel, String tel, Date anniversaire, String motdepasse, Set locations, Employe employe, Client client, Adresse adresse) {
       this.idmembre = idmembre;
       this.nomfamille = nomfamille;
       this.prenom = prenom;
       this.courriel = courriel;
       this.tel = tel;
       this.anniversaire = anniversaire;
       this.motdepasse = motdepasse;
       this.locations = locations;
       this.employe = employe;
       this.client = client;
       this.adresse = adresse;
    }
   
    public BigDecimal getIdmembre() {
        return this.idmembre;
    }
    
    public void setIdmembre(BigDecimal idmembre) {
        this.idmembre = idmembre;
    }
    public String getNomfamille() {
        return this.nomfamille;
    }
    
    public void setNomfamille(String nomfamille) {
        this.nomfamille = nomfamille;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getCourriel() {
        return this.courriel;
    }
    
    public void setCourriel(String courriel) {
        this.courriel = courriel;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public Date getAnniversaire() {
        return this.anniversaire;
    }
    
    public void setAnniversaire(Date anniversaire) {
        this.anniversaire = anniversaire;
    }
    public String getMotdepasse() {
        return this.motdepasse;
    }
    
    public void setMotdepasse(String motdepasse) {
        this.motdepasse = motdepasse;
    }
    public Set getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set locations) {
        this.locations = locations;
    }
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Adresse getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(Adresse adresse) {
        this.adresse = adresse;
    }




}


